url: "https://sensebox.de" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog

title: senseBox.de
sass:
    sass_dir: css
    style:    compressed

# Build settings
markdown: kramdown

# Project Tags
enableTags: true
tagarray: []

collections:
    events:
    projects: 
        output: true